{"timestamp": "2025-04-14 22:59:27", "name": "kma_chat_api", "level": "INFO", "message": "Application starting up - {\"mongodb_db\": \"kma_chat\", \"log_level\": \"INFO\"}"}
{"timestamp": "2025-04-14 22:59:44", "name": "kma_chat_api", "level": "INFO", "message": "Application shutting down"}
{"timestamp": "2025-04-14 22:59:46", "name": "kma_chat_api", "level": "INFO", "message": "Application starting up", "mongodb_db": "kma_chat", "log_level": "INFO"}
{"timestamp": "2025-04-14 23:00:12", "name": "kma_chat_api", "level": "INFO", "message": "Application shutting down"}
{"timestamp": "2025-04-14 23:00:14", "name": "kma_chat_api", "level": "INFO", "message": "Application starting up", "mongodb_db": "kma_chat", "log_level": "INFO"}
{"timestamp": "2025-04-14 23:03:56", "name": "kma_chat_api", "level": "INFO", "message": "Application shutting down"}
{"timestamp": "2025-04-14 23:03:58", "name": "kma_chat_api", "level": "INFO", "message": "Application starting up", "mongodb_db": "kma_chat", "log_level": "DEBUG"}
{"timestamp": "2025-04-14 23:04:02", "name": "kma_chat_api", "level": "INFO", "message": "Application shutting down"}
{"timestamp": "2025-04-14 23:04:07", "name": "kma_chat_api", "level": "INFO", "message": "Application starting up", "mongodb_db": "kma_chat", "log_level": "DEBUG"}
{"timestamp": "2025-04-14 23:04:13", "name": "kma_chat_api", "level": "INFO", "message": "Request received: POST /api/users/", "query_params": ""}
{"timestamp": "2025-04-14T16:04:13.936778", "name": "kma_chat_api", "level": "INFO", "message": "Request POST /api/users/ completed with status 422", "method": "POST", "url": "/api/users/", "status_code": 422, "processing_time_ms": 1.0008811950683594}
{"timestamp": "2025-04-14 23:06:29", "name": "kma_chat_api", "level": "INFO", "message": "Request received: POST /api/users/", "query_params": ""}
{"timestamp": "2025-04-14 23:06:29", "name": "kma_chat_api", "level": "INFO", "message": "Creating new user with student code: CT050413"}
{"timestamp": "2025-04-14T16:06:29.997806", "name": "kma_chat_api", "level": "INFO", "message": "DB find_one on users: success", "operation": "find_one", "collection": "users", "success": true}
{"timestamp": "2025-04-14T16:06:30.064689", "name": "kma_chat_api", "level": "INFO", "message": "DB insert_one on users: success", "operation": "insert_one", "collection": "users", "success": true, "data": {"inserted_id": "67fd328548fa740cf0a04420"}}
{"timestamp": "2025-04-14 23:06:30", "name": "kma_chat_api", "level": "INFO", "message": "User created successfully", "user_id": "67fd328548fa740cf0a04420", "student_code": "CT050413"}
{"timestamp": "2025-04-14 23:06:30", "name": "kma_chat_api", "level": "ERROR", "message": "Unhandled exception in POST /api/users/", "error": "1 validation error for UserResponse\nid\n  Field required [type=missing, input_value={'student_code': 'CT05041...fd328548fa740cf0a04420'}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.11/v/missing", "processing_time_ms": 889.193058013916, "exception": "Traceback (most recent call last):\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py\", line 147, in call_next\n    message = await recv_stream.receive()\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/anyio/streams/memory.py\", line 126, in receive\n    raise EndOfStream from None\nanyio.EndOfStream\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/hoang.van.giang/Projects/kma_chat/kma_chat_agent/KMA Chat Agent/src/app/middleware/logging_middleware.py\", line 23, in dispatch\n    response = await call_next(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py\", line 153, in call_next\n    raise app_exc\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py\", line 140, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/starlette/middleware/cors.py\", line 93, in __call__\n    await self.simple_response(scope, receive, send, request_headers=headers)\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/starlette/middleware/cors.py\", line 144, in simple_response\n    await self.app(scope, receive, send)\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/starlette/middleware/exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/starlette/routing.py\", line 714, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/starlette/routing.py\", line 734, in app\n    await route.handle(scope, receive, send)\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/starlette/routing.py\", line 288, in handle\n    await self.app(scope, receive, send)\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/starlette/routing.py\", line 76, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/starlette/routing.py\", line 73, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/fastapi/routing.py\", line 301, in app\n    raw_response = await run_endpoint_function(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/fastapi/routing.py\", line 212, in run_endpoint_function\n    return await dependant.call(**values)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/hoang.van.giang/Projects/kma_chat/kma_chat_agent/KMA Chat Agent/src/app/routers/users.py\", line 44, in create_user\n    return UserResponse(**created_user)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/pydantic/main.py\", line 253, in __init__\n    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\npydantic_core._pydantic_core.ValidationError: 1 validation error for UserResponse\nid\n  Field required [type=missing, input_value={'student_code': 'CT05041...fd328548fa740cf0a04420'}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.11/v/missing"}
{"timestamp": "2025-04-14 23:14:35", "name": "kma_chat_api", "level": "INFO", "message": "Application shutting down"}
{"timestamp": "2025-04-14 23:14:37", "name": "kma_chat_api", "level": "INFO", "message": "Application starting up", "mongodb_db": "kma_chat", "log_level": "DEBUG"}
{"timestamp": "2025-04-14 23:14:40", "name": "kma_chat_api", "level": "INFO", "message": "Request received: POST /api/users/", "query_params": ""}
{"timestamp": "2025-04-14 23:14:40", "name": "kma_chat_api", "level": "INFO", "message": "Creating new user with student code: CT050413"}
{"timestamp": "2025-04-14T16:14:40.984971", "name": "kma_chat_api", "level": "INFO", "message": "DB find_one on users: success", "operation": "find_one", "collection": "users", "success": true}
{"timestamp": "2025-04-14T16:14:41.059651", "name": "kma_chat_api", "level": "INFO", "message": "DB insert_one on users: success", "operation": "insert_one", "collection": "users", "success": true, "data": {"inserted_id": "67fd3470e7ffc84171020c19"}}
{"timestamp": "2025-04-14 23:14:41", "name": "kma_chat_api", "level": "INFO", "message": "User created successfully", "user_id": "67fd3470e7ffc84171020c19", "student_code": "CT050413"}
{"timestamp": "2025-04-14 23:14:41", "name": "kma_chat_api", "level": "ERROR", "message": "Unhandled exception in POST /api/users/", "error": "1 validation error for UserResponse\nid\n  Field required [type=missing, input_value={'student_code': 'CT05041...fd3470e7ffc84171020c19'}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.11/v/missing", "processing_time_ms": 847.5890159606934, "exception": "Traceback (most recent call last):\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py\", line 147, in call_next\n    message = await recv_stream.receive()\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/anyio/streams/memory.py\", line 126, in receive\n    raise EndOfStream from None\nanyio.EndOfStream\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/hoang.van.giang/Projects/kma_chat/kma_chat_agent/KMA Chat Agent/src/app/middleware/logging_middleware.py\", line 23, in dispatch\n    response = await call_next(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py\", line 153, in call_next\n    raise app_exc\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py\", line 140, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/starlette/middleware/cors.py\", line 93, in __call__\n    await self.simple_response(scope, receive, send, request_headers=headers)\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/starlette/middleware/cors.py\", line 144, in simple_response\n    await self.app(scope, receive, send)\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/starlette/middleware/exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/starlette/routing.py\", line 714, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/starlette/routing.py\", line 734, in app\n    await route.handle(scope, receive, send)\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/starlette/routing.py\", line 288, in handle\n    await self.app(scope, receive, send)\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/starlette/routing.py\", line 76, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/starlette/routing.py\", line 73, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/fastapi/routing.py\", line 301, in app\n    raw_response = await run_endpoint_function(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/fastapi/routing.py\", line 212, in run_endpoint_function\n    return await dependant.call(**values)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/hoang.van.giang/Projects/kma_chat/kma_chat_agent/KMA Chat Agent/src/app/routers/users.py\", line 47, in create_user\n    return UserResponse(**created_user)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/hoang.van.giang/Library/Caches/pypoetry/virtualenvs/kma-chat-agent-utlu7k3g-py3.12/lib/python3.12/site-packages/pydantic/main.py\", line 253, in __init__\n    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\npydantic_core._pydantic_core.ValidationError: 1 validation error for UserResponse\nid\n  Field required [type=missing, input_value={'student_code': 'CT05041...fd3470e7ffc84171020c19'}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.11/v/missing"}
{"timestamp": "2025-04-14 23:14:59", "name": "kma_chat_api", "level": "INFO", "message": "Application shutting down"}
